### ISSUE TITLE
Feat: Parquet Clean

### ISSUE THREAD

**Issue by KKould** [from-the-basement/elsm#27]
## Feature Request

When Version is destroyed and there are SSTs that are not needed by other versions, they will be cleared.

**Comment by ethe** [comment]
## 思路

由一个Cleaner异步线程在后台进行监听，内部主要的数据结构为BTreeMap(version号码为key)

Compaction发生后将delete的edit中的table gens发送至Cleaner进行注册，而当Version进行析构时，将自己的版本号发送至cleanner，cleaner接收到版本号时会先将自己版本号对应的node的状态修改为已析构后，再持续peek元素，并将持续删除至未析构的版本
![未命名文件](https://github.com/from-the-basement/elsm/assets/12211036/c2e36dbc-af95-4991-9b32-97368a119825)
